#index:
#    path: /
#    defaults: { _controller: 'App\Http\Controllers\DefaultController::index' }

-index:
  path: /
  defaults: {_controller: 'App\Http\Controllers\Api\NeuralNetworkController::test'}

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc"